export enum SagaActions {
	// CARTS
	FETCH_LIST_MOVIE_IN_CART = 'FETCH_LIST_MOVIE_IN_CART',
	REMOVE_MOVIE_BY_ID = 'REMOVE_MOVIE_BY_ID',
	ADD_MOVIE_BY_ID = 'ADD_MOVIE_BY_ID',
	// MOVIES
	GET_DETAIL_MOVIE_BY_ID = 'GET_DETAIL_MOVIE_BY_ID',
	GET_VIDEO_MOVIE_BY_ID = 'GET_VIDEO_MOVIE_BY_ID',
	GET_LIST_MOVIES = 'GET_LIST_MOVIES',
}
